language: bash

sudo: required

services:
  - docker

addons:
  hosts:
    - localhost

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - docker build -t scholzj/qpid-cpp:0.34 .
  - sudo docker run -P -d scholzj/qpid-cpp:0.34
  - sudo docker ps
  - bats tests.bats
