language: bash

sudo: required

services:
  - docker

addons:
  hosts:
    - localhost

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo add-apt-repository ppa:qpid/released  --yes
  - sudo apt-get update -q
  - sudo apt-get install -q libsasl2-2 libsasl2-modules libsasl2-modules-db
  - sudo apt-get install -q bats
  - sudo apt-get install -q qpid-tools

script:
  - docker build -t scholzj/qpid-cpp:travis .
  - bats tests.bats

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag scholzj/qpid-cpp:travis docker.io/scholzj/qpid-cpp:1.35.0-beta; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push docker.io/scholzj/qpid-cpp:1.35.0-beta; fi
