language: bash

sudo: required

services:
  - docker

addons:
  hosts:
    - localhost

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo add-apt-repository ppa:qpid/released  --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats qpid-tools sasl2-bin libsasl2-modules

script:
  - docker build -t scholzj/qpid-cpp:travis .
  - sudo docker run -P -d scholzj/qpid-cpp:travis
  - sudo docker ps
  - bats tests.bats
